[package]
authors = ["Hayato Ito <hayato@google.com>"]
name = "icfp2006"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.26.2"
env_logger = "0.4.3"
log = "0.3.8"
loggerv = "0.4.0"
regex = "0.1"
structopt = "0.1.1"
structopt-derive = "0.1.1"
